### ISSUE TITLE
WIP aur/python-deadlib

### ISSUE THREAD

**Issue by xiota** [Vekhir/AUR-python-deadlib#1]
<details><summary>Here's the PKGBUILD I have so far.</summary>

```
# Maintainer:

_pkgname="python-deadlib"
pkgbase="$_pkgname"
pkgname=("$_pkgname")
pkgdesc="Standard library redistribution"
pkgver=3.13.0
pkgrel=1.1
url="https://github.com/youknowone/python-deadlib"
license=('PSF-2.0')
arch=('any')

depends=(
  'python'
)
makedepends=(
  'python-build'
  'python-installer'
  'python-setuptools'
  'python-wheel'
)

_pkgsrc="$_pkgname-$pkgver"
_pkgext="tar.gz"
source=("$_pkgsrc.$_pkgext"::"$url/archive/refs/tags/v$pkgver.$_pkgext")
sha256sums=('bde43692d5a1de2a33777ff99f4c4344f7cca3a49362b2484a13870706194613')

build() {
  for i in ${_modules[@]}; do
    pushd "$_pkgsrc/${i%%::*}"
    python -m build --wheel --no-isolation --skip-dependency-check
    popd
  done
}

_modules=(
  'aifc'::'python-standard-chunk'
  'asynchat'
  'asyncore'
  'cgi'
  'cgitb'
  'chunk'
  'crypt'
  'imghdr'
  'mailcap'
  'nntplib'
  'pipes'
  'smtpd'
  'sndhdr'
  'sunau'
  'telnetlib'
  'uu'
  'xdrlib'
)

for i in "${_modules[@]}"; do
  _modulename="python-standard-${i%%::*}"
  _depends+=("$_modulename")

  _deps=()
  if [ "${i%%::*}" != "${i##*::}" ]; then
    _deps=("$(sed -E 's&,\s*& &g' <<< "${i##*::}")")
  fi

  pkgname+=("$_modulename")
  eval "$(cat << END
    package_${_modulename}() {
      pkgdesc+=" - ${i%%::*}"
      depends=(python ${_deps[@]})

      provides+=('python-${i%%::*}')
      conflicts+=('python-${i%%::*}')

      cd "\$_pkgsrc/${i%%::*}"
      python -m installer --destdir="\$pkgdir/" dist/*.whl
    }
END
  )"
done

eval "$(cat << END
    package_python-deadlib() {
      pkgdesc+=" - metapackage"
      depends=(${_depends[@]})
    }
END
  )"
```
</details>

**Comment by xiota** [comment]
BTW, `python-standard-chunk` and `python-standard-aifc` need to be disabled or deleted before `python-deadlib` can be switched to split packaging.  To disable, convert to metapackage:
```
Maintainer:

_newpkg="python-standard-aifc"
pkgbase="python-standard-aifc"
pkgname=python-standard_aifc"
pkgdesc="metapackage - switch to $_newpkg"
pkgver=3.13.0
pkgrel=2
arch=('any')

package() {
  depends=("$_newpkg")
}
```

**Comment by Vekhir** [comment]
Regarding the PKGBUILD:
I haven't actually thought about `python-deadlib` as a package itself. It's not like one could really _depend_ on it. So maybe it's more like a group?

I'm not convinced that mixing package names and their dependencies in this way is a good way forward. It feels like a bad precedent to set. I think the map based approach is more extensible. It does rely on bash though, so your approach is more flexible with other shells. Is that a consideration?
On a more practical note, the encoding and decoding with `sed` seems really complex and it's not really readable.
So, good idea in principle, but has some shortcomings. My version is admittedly the first thing that worked, so maybe I'm missing an edge case.
I like the use of `END` for the here doc.

As to the existing packages:
You seem very adamant about their removal. Can you please explain the context of your request, because I can't follow you. It seems non-sensical to me. That doesn't mean that it is, I don't even know what problem it is supposed to solve.

**Comment by xiota** [comment]
I am *not* "adamant" about removing the existing packages.  It is a requirement to switch python-deadlib to split packaging because multiple pkgbases cannot create the same package.  So they must be disabled or removed *prior* to the switch.

The plan to switch to split package was because you and micwoj92 prefer it.  But packages you control are blocking it.  It also seems micwoj92 has second thoughts about split packaging.  Since both of you have qualms about switching to split packaging, the package can stay as is.  Keeping it as a unified package does have benefits.

The problem with arrays is multiple arrays are needed, each containing duplicate information.  The format I'm using can be extended.
```
example='package'::'description'::'depends'
_pkg="$(sed -E 's&^(.*)::(.*)::(.*)$&\1&' <<< "$example")" 
_desc="$(sed -E 's&^(.*)::(.*)::(.*)$&\2&' <<< "$example")" 
_deps="$(sed -E 's&^(.*)::(.*)::(.*)$&\3&' <<< "$example")" 

echo "_pkg = $_pkg"
echo "_desc = $_desc"
echo "_deps = $_deps"
```

**Comment by xiota** [comment]
Split packages that don't include the pkgbase as a subpackage are difficult to find, which makes building and installing very difficult for users.  So I try to include the pkgbase as a metapackage to avoid this issue.

Try to build `aur/flutter` for an extreme example.

**Comment by Vekhir** [comment]
> I am not "adamant" about removing the existing packages. It is a requirement to switch python-deadlib to split packaging because multiple pkgbases cannot create the same package. So they must be disabled or removed prior to the switch.

Yes, _adamant_ was a bad choice of words. I wanted to bring across that I noticed you pushing in almost every message for the deletion of packages without really explaining the reasoning behind it. But you were not adamant, that's true, as we didn't have a chance to talk about it.

> The plan to switch to split package was because you and micwoj92 prefer it.

You asked for my opinion and I gave it to you. I'm still of this opinion and would like to see it become reality. It seemed you agreed with this opinion at some point.

> But packages you control are blocking it.

We don't even agree on what the PKGBUILD for this package should look like. Not an insurmountable issue, but starting to delete packages __now__, when we don't have a replacement seems ill thought out to me, perhaps rushed, despite there being no time pressure. So please don't try to paint this as me blocking progress for no reason.

> It also seems micwoj92 has second thoughts about split packaging.  Since both of you have qualms about switching to split packaging, the package can stay as is.

micwoj92 mostly has second thoughts about the package as a whole: `After some thought, I am still against this package.` I don't see how keeping things as is would change any of that, but that's something to ask them.
As for me, I don't have an issue with switching to split packaging - I disagree with the way to get there.

At last, I want your opinion: Would you like to see the move to a split package?

**Comment by Vekhir** [comment]
> Split packages that don't include the pkgbase as a subpackage are difficult to find, which makes building and installing very difficult for users. So I try to include the pkgbase as a metapackage to avoid this issue.

Seems like a tooling issue to me? I regularly do `pacman -U *.pkg.tar.zst` after removing unneeded packages. Of course, a clever tool might want to look into the .SRCINFO to see which packages are built. Maybe I'm missing something, but I'd rather have a clean package which can be well-supported later than provide hacks and workarounds for people that could know better.

> Try to build `aur/flutter` for an extreme example.

Building `aur/flutter` is complex, but I don't see how the metapackage makes it better or worse.

The issue I have with a metapackage is that after installing it, it's difficult to uninstall unneeded dependencies. Especially if someone decides to be lazy and just depend on the metapackage, despite only requiring parts of it. Our packages are essentiallly unrelated to each other.
If you want, we can do the [Plasma](https://wiki.archlinux.org/title/KDE#Installation) compromise: Have a `python-deadlib-meta` metapackage and a `python-deadlib` group. Then everyone can choose what they want.

**Comment by Vekhir** [comment]
> The problem with arrays is multiple arrays are needed, each containing duplicate information. The format I'm using can be extended.

What we'd really need are classes, but that's not going to happen.
I like the locality of your format, which is linked to the wish of avoiding duplicate information. Yet, I'm still sceptical of the decoding process. It's overly complex for something that should basically be a member access. 
Also, I agree that some information is duplicated with the array approach. While it's hardly to be expected that the names will change, that can be said of just about any other approach too. I don't like the array stuff either, but it feels less hacky than trying to implement a parser in bash.

As a point of interest, I ran your example with the string `'package'`:
```
$ example='package'
$ _deps="$(sed -E 's&^(.*)::(.*)::(.*)$&\3&' <<< "$example")"
$ echo "_deps = $_deps"
_deps = package
```
It seems only fixable by either appending `::::` to every package name or making the decoding even more complex, which I don't expect to make readability any better.

**Comment by xiota** [comment]
I generally prefer keeping packages unified, but was willing to split python-deadlib because thought it could be justified.  For now, because of practical issues, will leave it as a unified package.

-----

I initially asked your opinion on splitting because your packages would have to be deleted before a split could proceed.  I mentioned deleting the existing packages multiple times because you didn't respond to the first one, but stated you were ready to switch.

We don't need full agreement on everything.  Practically, the opinion of the primary maintainer of a package matters more, as far as that package is concerned.  For instance, your opinion on what to do with the existing packages matters more than mine.  If you are unwilling to delete or disable them *first*, splitting python-deadlib becomes impossible and specific details about how to do so don't matter.  Same applies to anyone who creates more of the other conflicting packages.

I had a split PKGBUILD that I was satisfied with, so the blocker was your packages.  An alternate route would have been for someone to open deletion requests against the conflicting packages.  I saw someone try that before.  He is now banned from AUR (for other reasons).  It was disrespectful, anti-user, and took a year to resolve.  I would rather call off proceeding with a split.

The problem with aur/flutter is it depends on packages that are created by a pkgbase with completely different name from any of the subpackages.  Packages are difficult to build without finding the pkgbase first.  Even AUR helpers have difficulty finding it.  The problem is solved by naming one of the subpackages the same as the pkgbase.  python-deadlib-meta would not work.  Neither would groups.

Whatever personal issues people might have with a metapackage don't matter because there is no need to install it.  It would exist to solve a specific issue related to using AUR packages.

<details><summary>Current split package candidate.</summary>

```
# Maintainer:

_pkgname="python-deadlib"
pkgbase="$_pkgname"
pkgname=("$_pkgname")
pkgdesc="Standard library redistribution"
pkgver=3.13.0
pkgrel=2
url="https://github.com/youknowone/python-deadlib"
license=('PSF-2.0')
arch=('any')

depends=(
  'python'
)
makedepends=(
  'python-build'
  'python-installer'
  'python-setuptools'
  'python-wheel'
)

_pkgsrc="$_pkgname-$pkgver"
_pkgext="tar.gz"
source=("$_pkgsrc.$_pkgext"::"$url/archive/refs/tags/v$pkgver.$_pkgext")
sha256sums=('bde43692d5a1de2a33777ff99f4c4344f7cca3a49362b2484a13870706194613')

build() {
  for i in ${_modules[@]}; do
    pushd "$_pkgsrc/${i%%::*}"
    python -m build --wheel --no-isolation --skip-dependency-check
    popd
  done
}

_modules=(
  'aifc'::'python-audioop,python-standard-chunk'
  'asynchat'::'python-standard-asyncore'
  'asyncore'::
  'cgi'::
  'cgitb'::
  'chunk'::
  'crypt'::
  'imghdr'::
  'mailcap'::
  'nntplib'::
  'pipes'::
  'smtpd'::'python-standard-asynchat,python-standard-asyncore'
  'sndhdr'::'python-standard-aifc'
  'sunau'::
  'telnetlib'::
  'uu'::
  'xdrlib'::
)

for i in ${_modules[@]}; do
  _modulename="python-standard-${i%%::*}"
  _depends+=("$_modulename")
  _deps=("$(sed -E 's&,\s*& &g' <<< "${i##*::}")")

  pkgname+=("$_modulename")
  eval "$(cat << END
    package_${_modulename}() {
      pkgdesc+=" - ${i%%::*}"
      depends=(python ${_deps[@]})

      provides+=('python-${i%%::*}')
      conflicts+=('python-${i%%::*}')

      cd "\$_pkgsrc/${i%%::*}"
      python -m installer --destdir="\$pkgdir/" dist/*.whl
    }
END
  )"
done

eval "$(cat << END
    package_python-deadlib() {
      pkgdesc+=" - metapackage"
      depends=(${_depends[@]})
    }
END
  )"
```
</details>

**Comment by Vekhir** [comment]
Let's keep things as they are. I agree, that's the best path forward.
